spring.datasource.url=jdbc:postgresql://demobackendolimpiadas-jfjmjf:5432/cursos_backend
spring.datasource.username=ari
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
server.port=8080